# Generated by Django 3.2.7 on 2021-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], max_length=20, null=True),
        ),
    ]
